grails:
    profile: web
    codegen:
        defaultPackage: grace.guides
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'


